language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.4
        - os: linux
          sudo: required
          python: 3.5
        - os: linux
          sudo: required
          python: 3.6

install: 
   - cd python && pip install .

# command to run tests
script:
  - cd python && python test.py
